apiVersion: v1
kind: Service
metadata:
  name: sm-data-governance
  namespace: sm-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8300
      targetPort: http
  selector:
    app: sm-data-governance
